name: 'Setup'
description: 'Run basic setup'

runs:
  using: 'composite'
  steps:
    - name: Cache Dependencies
      id: cache
      uses: actions/cache@v2
      with:
        path: |
          node_modules
          tools/src/**/*.js
        key: dependencies-${{ runner.os }}-${{ hashFiles('yarn.lock', 'tools/src/**/*.ts') }}
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Install
      if: steps.cache.outputs.cache-hit != 'true'
      shell: bash
      run: yarn
    - name: Setup git user
      shell: bash
      run: git config user.email "-" && git config user.name "🤖 ns3 CI/CD"
