name: Check
on:
  pull_request:
env:
  NX_CLOUD_DISTRIBUTED_EXECUTION_AGENT_COUNT: 3

jobs:
  controller:
    name: Controller
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
        with:
          affected: true
      - run: npx nx-cloud start-ci-run
      - name: Run Commands
        uses: ./.github/actions/run-commands-in-parallel
        with:
          parallel-commands-on-agents: |
            npx nx affected --target=build --parallel=3
            npx nx affected --target=lint --parallel=3 --silent
            npx nx affected --target=test --parallel=3 --quiet
            npx nx affected --target=tsd --parallel=3
      - run: npx nx-cloud stop-all-agents
        if: ${{ always() }}

  agents:
    name: Agent
    runs-on: ubuntu-latest
    timeout-minutes: 60
    strategy:
      matrix:
        agent: [1, 2, 3]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: ./.github/actions/setup
      - name: Start Nx Agent ${{ matrix.agent }}
        run: npx nx-cloud start-agent
