name: Publish
concurrency:
  group: ${{ github.workflow }}-${{ github.event.inputs.stage }}
  cancel-in-progress: false
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to checkout and publish'
        required: true
        default: master
        type: string
      versionSuffix:
        description: 'Version suffix to append to published version'
        required: true
        default: 1
        type: string

jobs:
  main:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.version }}
      - name: Setup
        uses: ./.github/actions/setup
      - name: Publish
        run: yarn nx affected --target publish --parallel 3 --all
        env:
          NPM_PACKAGE_TAG: ${{ github.event.inputs.version }}
          NPM_PACKAGE_VERSION: ${{ github.event.inputs.version }}.${{ github.event.inputs.versionSuffix }}
