name: Release
concurrency:  ${{ github.workflow }}-${{ github.ref }}
on:
  push:
    branches:
      - master
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  controller:
    name: Controller
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        run: |
          echo "NX_BASE=last-release" >> $GITHUB_ENV
          echo "NX_HEAD=${{ github.sha }}" >> $GITHUB_ENV
      - name: Version
        run: yarn nx affected --target=version
      - name: Tag last-release
        run: git tag -f last-release
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
