name: Release
on:
  push:
    branches:
      - master
      - develop
      - 'alpha/*'
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        uses: ./.github/actions/setup
      - name: Start Release
        id: semantic
        run: npx semantic-release --dry-run
      - name: Build
        run: yarn nx affected --target build --parallel --base ${{ steps.semantic.outputs.last-head || 'HEAD' }}
      - name: Publish
        run: yarn nx affected --target publish --parallel --base ${{ steps.semantic.outputs.last-head || 'HEAD' }} --pkgVersion ${{ steps.semantic.outputs.next-version }} --tag ${{ steps.semantic.outputs.channel }} --exclude di
      - name: Finish Release
        run: npx semantic-release
